NAME = ft_display_file

FLAG = -Wall -Wextra -Werror

SRC = ft_display_file.c

OBJ = *.o

all: ${NAME}
${NAME}:
	gcc ${FLAG} -o ${NAME} ${SRC} 

clean: 
	/bin/rm -f ${OBJ}

fclean: clean
	/bin/rm -f ${NAME}
